### ISSUE TITLE
Instagram package seems broken

### ISSUE THREAD

**Issue by RuneAndersen** [Orckestra/CMS-Packages#10]
Hi there

I've tried installing and following the installation process of the Instagram package, but can't seem to get it to work.

The C1 documentation doesn't seem to be aligned with the current Instagram layout and it seems like Instagram made some API updates at least to the documentation during November.

I'm not entirely sure, but it seems to me as if Instagram changed something in relation to authentication and might also endpoint addresses.
When trying to use the following functions the C1 log shows these errors:
- RecentPhotos: The remote server returned an error: (400) Bad Request.
- MostPopular: The remote server returned an error: (404) Not Found.

Could you please have a go and see if there is something broken. If it should work, then please consider updating the guide as there must be something missing.

I was able to reproduce the error like this:
- Create new C1 demosite
- Install Instagram package
- following guide for instagram account modifications
- adding instagram info to C1 console, content section
- adding RecentPhotos or MostPopular function to page.

/Rune

**Comment by RuneAndersen** [comment]
Bonus info:
On instagram developers, edit the client. If I uncheck the "Disable implicit OAuth" and go through this tutorial http://bobmckay.com/web/simple-tutorial-for-getting-an-instagram-clientid-and-access-token/
I can get an access token and have successful calls to Instagram API using URLs like
https://api.instagram.com/v1/users/self/media/recent/?access_token=MYTOKEN

I've tried it out via the https://www.getpostman.com/

**Comment by RuneAndersen** [comment]
Found at least one error, so here goes.

The api.UsersSearch function has a bad URL compared to the current API https://www.instagram.com/developer/endpoints/users/#get_users_search

So if I remove this part from the RecentPhotos Razor function
`var responseUser = api.UsersSearch(UserName, "100", null);
if (responseUser == null) {
    <div class="alert alert-danger">Instagram User not found.</div>
    return;
}
var userId = "";
foreach (var user in responseUser.data) {
    if (user.username == UserName) {
        userId = user.id;
        break;
    }
}`

and make the API call like this:
`response = api.UserRecentMedia("self", string.Empty, Request.QueryString["id"] == FunctIdentificator.GetHashCode().ToString() ? Request.QueryString["next"] : null, null, null, null, "My secret auth code");`

I can get it to work :-)

**Comment by InnaBoitsun** [comment]
@RuneAndersen, according to the new Instagram Policy  https://www.instagram.com/developer/
"You cannot replicate the core user experience of the Instagram apps or web site. For example, do not build a media viewer." 
So popably the package is outdated, but we are looking to that questing...
