### ISSUE TITLE
[Composite.AspNet.MvcFunctions] Error at MVC Functions addon when using TempData

### ISSUE THREAD

**Issue by identify1980** [Orckestra/CMS-Packages#21]
I am using the MVC Functions AddOn in a project. Whenever I try to put something to the controller TempData an error is thrown.

"The SessionStateTempDataProvider class requires session state to be enabled."

The error is thrown, when "ProcessRequest" is called inside of MvcFunctionBase.ExecuteRoute.

**Comment by mawtex** [comment]
Judging from the message you are getting, you can probably solve the issue with a general (non C1-specific) sollition, like http://stackoverflow.com/questions/720367/the-sessionstatetempdataprovider-requires-sessionstate-to-be-enabled

**Comment by identify1980** [comment]
Hi - me again after a while. I tried every option being named in your link and the links within - none worked. Then I did some more debugging and that's what I found:

1) The Session is already working. I double-checked it in IIS as well as by logging the HttpContext.Current.Session from a C1-Page without any MVC function in it
2) HttpContext.Current.Session from within a MVC controller is not null as well - in fact it is the same object as in (1)
3) this.Session within a MVC controller has the Session property being NULL
4) this.HttpContext (an instance of HttpContextWrapper) within a MVC controller has the Session property being NULL
5) In MvcFunctionBase.cs the HttpContext from (4) is created with a new HttpContext.

The session seems to get lost in (5). Don't know if it may be right, but maybe SessionStateUtility.AddHttpSessionStateToContext (https://msdn.microsoft.com/en-us/library/system.web.sessionstate.sessionstateutility.addhttpsessionstatetocontext(v=vs.110).aspx) is a solution?

**Comment by napernik** [comment]
Hi @identify1980 I made a fix, if you uninstall the MvcFunctions package, and install a new version (1.0.8), it should be fixed. https://github.com/Orckestra/C1-Packages/commit/6c197dea56f60bf361fa2a23675f13be3982d32e

**Comment by identify1980** [comment]
Hi @napernik - I tested the changes and it works as expected now - but only after I compiled it on my own. Whatever is in your build-process - the copy-method you made is not in your DLL. Instead one line (the user-referring one) is integrated in place where the original method call was made, while the other one (the session-related one) misses (I decompiled the DLL to check it). So to sum it up: if I compile on my own, it works well - but with the shipped DLL from the package it does not.

`HttpResponse response = new HttpResponse((TextWriter) stringWriter);
        HttpContext httpContext = new HttpContext(current.Request, response);
        RequestContext requestContext = new RequestContext((HttpContextBase) new HttpContextWrapper(httpContext), routeData);
        httpContext.User = current.User; // <-- this line remains from your method "CopyHttpContextToData"
        IHttpHandler httpHandler = routeData.RouteHandler.GetHttpHandler(requestContext);
        Verify.IsNotNull((object) httpHandler, "No handler found for the function '{0}'", (object) (this.Namespace + "." + this.Name));`

**Comment by napernik** [comment]
Hi @identify1980 thanks for finding this out, I've published a new version with a fix - 1.0.9
