### ISSUE TITLE
[Composite.Tools.PackageCreator] Can't delete a page tree added to a package

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/CMS-Packages#37]
**Repro**:

1. Create a package.
2. From the Content perspective, right-click the home page and click "Add This Page Tree to Package Creator"
3. Now in the Package Creator perspective, expand the package > "Page Trees"
4. Try and delete the added page tree.

**Expected**: The node is deleted fromt he package
**Actual**: Nothing happens. The page tree node is still there.

**Comment by InnaBoitsun** [comment]
[Composite.Tools.PackageCreator] - 3.6.8 - fix bug #37 - Can't delete a page tree added to a package

**Comment by wwwysocki** [comment]
Verified on v.3.6.8
