### ISSUE TITLE
[Composite.Tools.PackageCreator] Can add SQL Connections and SQL Functions (queries) as individual data items

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/CMS-Packages#38]
Repro:

1. Create an SQL function.
2. Add the SQL Connection node and the SQL function to the Package Creator
3. Check the package in the Package Creator perspective.

Expected: 

Option 1. SQL Functions are added as Functions
Option 2. SQL Functions can't be added to Package Creator.

Actual:

Both SQL Connections and SQL Function below are added as individual data items.

![sql-functions-in-package-creator](https://cloud.githubusercontent.com/assets/14821915/20176085/c18df596-a74e-11e6-9750-9ffaee77fbbf.png)

**Comment by mawtex** [comment]
I'll close this with "wontfix". SQL Functions - I don't think this will be a loss to not support, since it my impression it is hardly used anymore (if at all). We should even consider pulling SQL Functions from the core install.

**Comment by wwwysocki** [comment]
Still, it would be nice to have the menu items "Add to Package Creator" and "Exclude from Package Creator" on SQL Connections and SQL Queries removed.
