### ISSUE TITLE
[Composite.Web.BundlingAndMinification] Order of bundled JavaScript files are wrong

### ISSUE THREAD

**Issue by aeont** [Orckestra/CMS-Packages#42]
Because of the bug in System.Web.Optimization  1.1.0 order of bundled JavaScript files are wrong, i.e. it's not keep the order of added files.

I've tried:
1) Upgrade System.Web.Optimization  1.1.0  to 1.1.4 - doesn't work for me https://www.nuget.org/packages/Microsoft.AspNet.Web.Optimization
2) Using workaround:

`    public class AsIsBundleOrderer : IBundleOrderer
    {
        public virtual IEnumerable<BundleFile> OrderFiles(BundleContext context, IEnumerable<BundleFile> files)
        {
            return files;
        }
    }

    public static class BundleExtensions
    {
        public static Bundle ForceOrdered(this Bundle sb)
        {
            sb.Orderer = new AsIsBundleOrderer();
            return sb;
        }
    }`

and than:

`BundleTable.Bundles.Add(sb.ForceOrdered());`

more details: http://stackoverflow.com/questions/11979718/how-can-i-specify-an-explicit-scriptbundle-include-order/11981271

doesn't work for me.

3) Tried this - BundleTable.Bundles.FileSetOrderList, but was not able to complete.
http://stackoverflow.com/questions/10221475/how-to-apply-custom-bundle-order 

@napernik @mawtex your advice will be appreciated.

**Comment by aeont** [comment]
Seems like replacing 
var sb = new ScriptBundle(bundleVirtualPath);
to
var sb = new Bundle(bundleVirtualPath);

fixed the issue.. testing now..

**Comment by aeont** [comment]
@napernik @mawtex @InnaBoitsun fixed https://github.com/Orckestra/CMS-Packages/pull/43

**Comment by aeont** [comment]
@InnaBoitsun @mawtex @napernik this issue still NOT solved. Instead taking my proposal you implemented yourself just part of the solution, which seems not solved the problem. See my commit https://github.com/aeont/CMS-Packages/commit/10b8f5b4eb608ed344b96fe77b6eb37b3d177cee#diff-9990155f977c30012660963ed70310a1  - pay attention to the extension and ForceOrdered.

+ Another feature proposal here implement  data-c1-order - to control ordering in some cases.

**Comment by InnaBoitsun** [comment]
@aeont probably you have some specific file names when the order become wrong.  I tested the committed implementation with such specific JS libraries like jQuery.js and the order was correct.  Please provide your example of JS files you include on the page - just file names, no matter their content.
