### ISSUE TITLE
[Composite.Versioning.ContentVersioning] Pages deleted before an upgrade not restorable

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/CMS-Packages#53]
**Prepare:**

1. Have v. 5.0 website.
2. Have Content Versioning 2.4.1 installed. (2.4.1 is the max version for 5.0)

**Repro:**

1. Delete a page.
2. Make sure it appeared in the Content Modification Log
3. Upgrade the website to v.5.5 or later.
4. Upgrade Content Versioning to v. 2.6.0 or later (uninstall 2.4.1 and install 2.6.0)
5. Try and restore the deleted page from the Content Modification Log.

**Expected**: The page has been restored.
**Actual**: An error message pops up: "The given key was not present in the dictionary."

Note: The pages deleted after the upgrade (Steps 3-4) are restored OK.

**Comment by napernik** [comment]
Fixed in 2.6.2
