### ISSUE TITLE
[Composite.AspNet.MvcFunctions] Subroutes not found

### ISSUE THREAD

**Issue by identify1980** [Orckestra/CMS-Packages#56]
Since using the current C1 6.0 (patched with bugfix-branch) I can call pages with an mvc function in it. However - if the MVC function is registered via class attribute and there are sub actions in the controller I cannot access them anymore. It definitely worked with v5.0

Some example code below:

`
[C1Function(Namespace = "T2G.Account", Name = "Login", Description = "Displays a login form")]
public class LoginController : Controller
{
	[AllowAnonymous]
	public ActionResult Index(string returnUrl)
	{
		// some code
	}

	[AllowAnonymous]
	[HttpPost]
	[ValidateAntiForgeryToken]
	public ActionResult Index(UserLoginViewModel model)
	{
		// some code
		return this.RedirectToAction(
			"SendCode",
			new
			{
				rememberMe = model.RememberMe,
				returnUrl =
					string.IsNullOrWhiteSpace(returnUrl)
						? string.Empty
						: HttpUtility.UrlEncode(returnUrl)
			});
	}

	[AllowAnonymous]
	public ActionResult SendCode(bool rememberMe, string returnUrl)
	{
		// some code
	}
}
`

The page has the url "Login". The login form gets displayed. The POST also happens. But when I get redirected to "SendCode" ("/Login/SendCode?rememberMe=False"), I just get a 404.

**Comment by mawtex** [comment]
Closing this, since this is being worked on at https://github.com/Orckestra/C1-CMS-Foundation/issues/430
