### ISSUE TITLE
Something Wrong with the Feeds ??

### ISSUE THREAD

**Issue by vinayakwebdev** [Orckestra/CMS-Packages#58]
Hi There @mawtex,

I am a newbie with C1 CMS and I am following the Exact Same instructions from Here : [http://users.c1.orckestra.com/Functions/GuideToC1Functions/Test-Your-Knowledge](http://users.c1.orckestra.com/Functions/GuideToC1Functions/Test-Your-Knowledge)

to insert RSS feed reader 
and I am getting This Error : 

![livemode](https://user-images.githubusercontent.com/6002452/27842355-62fdd5ee-60d7-11e7-8b76-d7f74cf40ccf.JPG)

I have Latest CMS and all the system requirements but still couldn't find solution for that. I read somewhere on forum to use razor functions to overcome similar issue to this one but I have yet to learn Razor things I ma just following the Basics Training from main website.

After testing the function and installing and uninstalling etc i got this results :  

Markup Code : 
![markupcode](https://user-images.githubusercontent.com/6002452/27842560-ff0a7522-60d8-11e7-9126-bb6bcc699ea2.JPG)

Input Value: 
![testfunction](https://user-images.githubusercontent.com/6002452/27842562-ff0b807a-60d8-11e7-8ad6-18dd66e94f97.JPG)

Test Result: 
![testfunctionresult](https://user-images.githubusercontent.com/6002452/27842561-ff0b6fa4-60d8-11e7-9e7c-01f74282bf3d.JPG)

Moreover I Couldn't find Twitter function to even download and use

![twitterfeedfunctionnotavaiabletodownload](https://user-images.githubusercontent.com/6002452/27842597-4d6f58e0-60d9-11e7-8c6c-77689de4097e.JPG)

and Lastly I found this error on the Live website : 

![mainlivesiteerror](https://user-images.githubusercontent.com/6002452/27842615-7f20ae48-60d9-11e7-80a7-4f14635e92d2.JPG)

Please guide me and / or correct me if I am wrong on the path to learn CMS.

Please feel free to contact me for any required or additional details.

Thanks and Waiting for your reply,

Pratik

**Comment by napernik** [comment]
Hi Pratik

It is a know issue with 6.1 release. The fix is to update /bin/Orckestra.AspNet.Roslyn.dll
https://github.com/Orckestra/C1-CMS-Foundation/files/992573/Orckestra.AspNet.Roslyn.dll.zip

More details here:  https://github.com/Orckestra/C1-CMS-Foundation/issues/440

**Comment by vinayakwebdev** [comment]
Thanks Napernik.
