### ISSUE TITLE
Not able to see anything under “Available Packages”.  C1 V4.2

### ISSUE THREAD

**Issue by Santoshhk1** [Orckestra/CMS-Packages#62]
![cms available packages empty](https://user-images.githubusercontent.com/34513589/33943827-31621502-e040-11e7-9390-71f7485c17da.JPG)
I am new in Composite C1. I Strictly want to use C1 V4.2 and Add a add-on in it. When I try to add any add-on, everywhere under installation guide they say :=> Go to the "System" perspective. > Open the folders “Packages” | “Available Packages” | " Composite.Tools".

But problem with it is I am not able to see anything under **“Available Packages”**.

Anybody knows why is this problem?

Guys please do not ask to upgrade CMS C1 to any new version, because task (assignment) given to me is to add any add-on in CMS C1 V4.2 only.

Can anybody help me add any Add-on in CMS C1 V4.2 or any guide link to do it.

FYI I am trying to add "Composite.Tools.SqlServerDataProvider" add-on for now.

Any help is appreciated. Thank you in advance.

**Comment by InnaBoitsun** [comment]
When C1 CMS v. 5.0 was released, most of packages was updated to support new C1 CMS v. 5.0 UI, so they require minimum C1 version = 5.0, so you don't see any packages in Available Packages. 
For the Composite.Tools.SqlServerDataProvider packahe you can review package history here https://github.com/Orckestra/CMS-Packages/commits/master/Composite.Tools.SqlServerDataProvider and see when minimum version was changes, and download the package for the previous version. 
![image](https://user-images.githubusercontent.com/6649972/33991382-148d5be8-e0d7-11e7-9ba6-ab786ac3202b.png)

Try to download previous version by that link https://github.com/Orckestra/CMS-Packages/raw/13b9e4c5ea026207a787031f764f90f920d1e719/Composite.Tools.SqlServerDataProvider/Composite.Tools.SqlServerDataProvider/Release/Composite.Tools.SqlServerDataProvider.zip
and install package as local package.

**Comment by Santoshhk1** [comment]
Hi Inna,

Thank you for your help and the direct link there.

This helped me. 
Thank you once again.
