### ISSUE TITLE
[Composite.Community.Blog] Disqus comments and counts won't load if web-browser disables mixed mode content (https + http)

### ISSUE THREAD

**Issue by DBailey635** [Orckestra/CMS-Packages#63]
The JavaScript to enable Disqus commenting and comment counts uses http:// to load the required .js files. It needs to be ammended as follows to allow loading whenever the web-browser blocks mixed mode content. For the count, from this:

`s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';`

... to this:

`s.src = '//' + disqus_shortname + '.disqus.com/count.js';`

For the embed, from this:

`dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';`

... to this:

`dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';`

Thanks.

**Comment by mawtex** [comment]
Fixed via PR
