### ISSUE TITLE
[Composite.Web.Css.Sass] No longer supported in the C1 Console

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/CMS-Packages#9]
**Repro**:
1. Install the Composite.Web.Css.Sass package.
2. Add a *.sass file in the Layout perspective.
3. Try and edit it.

**Expected**:
- The sass file in the tree has a proper icon.
- You can edit the file (There is the Edit button.)

**Actual**:
- The sass file has a generic icon.
- No Edit button. Can't edit it in the C1 Console

**Comment by InnaBoitsun** [comment]
The console supports new .scss files. (.sass is old). I think we can close the bug
